---
language: "node_js"
node_js:
  - "0.10"
  - "0.12.1"
  - "0.12.2"
  - "0.12.3"
  - "0.12.4"
  - "0.12.5"
  - "0.12.6"
  - "0.12.7"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
  - "4.0"
  - "4.1"
sudo: false
